/* DYPD interpretation/consultation data and text provided by ClinPGx (https://www.clinpgx.org/page/dpydRefMaterials) [2026-07-14]
																													   YYYY-MM-DD
*/

#ifndef DYPD_INTERPRETATION_H
#define DYPD_INTERPRETATION_H

typedef struct {
    const char *phenotype;
    float score;
    const char *notation;
    const char *interpretation;
} interpretation_summary;

interpretation_summary dataset[] = {
    { "DPYD Poor Metabolizer", 2.0, "This result signifies that the patient has two copies of normal function DPYD alleles. Based on the genotype result this patient is predicted to be DPYD Normal Metabolizer with a DPYD activity score of 2. For this genotype, no selective dose adjustment is indicated for medications that are metabolized by DPD. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing.", "This result signifies that the patient has two copies of no function alleles of the DPYD gene. Based on the genotype result this patient is predicted to be a DPYD Poor Metabolizer with a DPYD activity score of 0. This patient may be at risk for adverse drug reactions to medications that are metabolized by DPD (i.e. 5-fluorouracil, capecitabine, and tegafur) and alternative therapeutic agents may be indicated. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing." },
    { "DPYD Poor Metabolizer", 1.5, "This result signifies that the patient has one copy of a normal function allele and one copy of a decreased function allele of the DPYD gene. Based on the genotype result this patient is predicted to be a DPYD Intermediate Metabolizer with a DPYD activity score of 1.5. This patient may be at risk for adverse drug reactions to medications that are metabolized by DPD (i.e. 5-fluorouracil, capecitabine, and tegafur) and a dose adjustment may be indicated. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing.", "This result signifies that the patient has two copies of no function alleles of the DPYD gene. Based on the genotype result this patient is predicted to be a DPYD Poor Metabolizer with a DPYD activity score of 0. This patient may be at risk for adverse drug reactions to medications that are metabolized by DPD (i.e. 5-fluorouracil, capecitabine, and tegafur) and alternative therapeutic agents may be indicated. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing." },
    { "DPYD Poor Metabolizer", 1.0, "This result signifies that the patient has either one copy of a normal function allele and one copy of a no function allele of the DPYD gene OR two copies of decreased function alleles of the DPYD gene. Based on the genotype result this patient is predicted to be a DPYD Intermediate Metabolizer with a DPYD activity score of 1. This patient may be at risk for adverse drug reactions to medications that are metabolized by DPD (i.e. 5-fluorouracil, capecitabine, and tegafur) and a dose adjustment may be indicated. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing.", "This result signifies that the patient has two copies of no function alleles of the DPYD gene. Based on the genotype result this patient is predicted to be a DPYD Poor Metabolizer with a DPYD activity score of 0. This patient may be at risk for adverse drug reactions to medications that are metabolized by DPD (i.e. 5-fluorouracil, capecitabine, and tegafur) and alternative therapeutic agents may be indicated. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing." },
    { "DPYD Poor Metabolizer", 0.5, "This result signifies that the patient has one copy of a decreased function allele and one copy of a no function allele of the DPYD gene. Based on the genotype result this patient is predicted to be a DPYD Poor Metabolizer with a DPYD activity score of 0.5. This patient may be at risk for adverse drug reactions to medications that are metabolized by DPD (i.e. 5-fluorouracil, capecitabine, and tegafur) and a dose adjustment or alternative therapeutic agents may be indicated. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing.", "This result signifies that the patient has two copies of no function alleles of the DPYD gene. Based on the genotype result this patient is predicted to be a DPYD Poor Metabolizer with a DPYD activity score of 0. This patient may be at risk for adverse drug reactions to medications that are metabolized by DPD (i.e. 5-fluorouracil, capecitabine, and tegafur) and alternative therapeutic agents may be indicated. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing." },
    { "DPYD Poor Metabolizer", 0.0, "This result signifies that the patient has two copies of no function alleles of the DPYD gene. Based on the genotype result this patient is predicted to be a DPYD Poor Metabolizer with a DPYD activity score of 0. This patient may be at risk for adverse drug reactions to medications that are metabolized by DPD (i.e. 5-fluorouracil, capecitabine, and tegafur) and alternative therapeutic agents may be indicated. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing.", "This result signifies that the patient has two copies of no function alleles of the DPYD gene. Based on the genotype result this patient is predicted to be a DPYD Poor Metabolizer with a DPYD activity score of 0. This patient may be at risk for adverse drug reactions to medications that are metabolized by DPD (i.e. 5-fluorouracil, capecitabine, and tegafur) and alternative therapeutic agents may be indicated. Please consult a clinical pharmacist for more information about how DPD metabolic status influences drug selection and dosing." },
    { NULL, 0.0, NULL, NULL }
};

#define DATASET_COUNT 5

#endif // DYPD_INTERPRETATION_H
