/* testing out htslib apis for bam reading 
   this will eventually be folded into main.c
   as part of the general API using htslib,
   and will be tied to the lookup logic code
   that references the existing allele tables 
   and bitmask

   much of my code references Vasudeva Sarma's
   'read_bam.c' from the htslib documentation

   I think it's a decent start - just need to tidy
   up the cleanup function and arrange it properly
   the fact it compiles is good enough. 

   not sure if I'm happy with the cleanup the way it 
   is at the moment, but i'll get around to changing 
   it later. 
*/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <getopt.h>
#include <stdint.h>
#include <htslib/sam.h>
#include "../includes/cyp2c19_allele_lut.h"


#define TARGET_COUNT 35
#define BASE_COUNT   5

static inline int is_target_position(int ref_pos){
     for (int i = 0; i < TARGET_COUNT; i++) {
        if (cyp2c19_allele_pos[i] == ref_pos) {
            return i;
        }
    }
    return -1;
}

static const uint8_t base_to_idx[16] = {
    [0]  = 4,  // 0 = invalid
    [1]  = 0,  // 1 = A
    [2]  = 1,  // 2 = C
    [3]  = 4,  // 3 = invalid 
    [4]  = 2,  // 4 = G
    [8]  = 3,  // 8 = T
    [15] = 4,  // 15 = N
};

static inline int base_to_index(uint8_t base_code) {
    return base_to_idx[base_code & 0xF];  /* mask to 4 bits */
}

void extract_variants(bam1_t *bamdata, sam_hdr_t *sam_hdr, uint32_t tally[TARGET_COUNT][BASE_COUNT]){
    int flag   = bamdata->core.flag;
    if (flag & 0x4 || flag & 0x100 || flag & 0x800) return; /* filtering unused/unnecessary flags: unmapped, secondary, supplementary  */
    int ref_pos = bamdata->core.pos + 1;  // 0-based to 1-based to match HGVS nomenclature + the existing array...
    int l_qseq = bamdata->core.l_qseq;  
    uint32_t *cigar     = bam_get_cigar(bamdata); 
    uint32_t seq_pos    = 0;
    uint8_t *seq = bam_get_seq(bamdata);
    

    int n_cigar = bamdata->core.n_cigar;

    for(int i = 0; i < n_cigar; i++){
        uint32_t op = cigar[i];
        int op_type = bam_cigar_op(op);
        int op_len  = bam_cigar_oplen(op);
        if (op_type == BAM_CMATCH || op_type == BAM_CEQUAL || op_type == BAM_CDIFF) {
            for (int k = 0; k < op_len; k++) {
                int variant_id = is_target_position(ref_pos);
                if (variant_id >= 0) {
                    uint8_t base_code = bam_seqi(seq, seq_pos);
                    int base_idx = base_to_index(base_code);
                    tally[variant_id][base_idx]++;
                }
                ref_pos++;
                seq_pos++;
            }
        } else if (op_type == BAM_CINS || op_type == BAM_CSOFT_CLIP) {
            seq_pos += op_len;
        } else if (op_type == BAM_CDEL || op_type == BAM_CREF_SKIP) {
            ref_pos += op_len;
        }
        
    }
}

void print_tally(FILE *fp, uint32_t tally[TARGET_COUNT][BASE_COUNT]) {
    fprintf(fp, "\n## Base Tally by Target Position\n\n");
    fprintf(fp, "| Variant ID | Position | A | C | G | T | N | Total |\n");
    fprintf(fp, "| :--- | :--- | ---: | ---: | ---: | ---: | ---: | ---: |\n");
    
    for (int i = 0; i < TARGET_COUNT; i++) {
        fprintf(fp, "| %d | %u | %u | %u | %u | %u | %u | %u |\n",
                i,
                cyp2c19_allele_pos[i],
                tally[i][0],  // A
                tally[i][1],  // C
                tally[i][2],  // G
                tally[i][3],  // T
                tally[i][4]); // N
    }
}

int file_read(int argc, char *argv[]) {

    uint32_t tally[TARGET_COUNT][BASE_COUNT] = {0};
    const char *inname = NULL;
    samFile *inputfile = NULL;
    FILE *fp           = fopen(argv[2], "w");
    if(!fp){
        fprintf(stderr, "Error: could not open writeable file\n");
        goto cleanup;
    }
    sam_hdr_t *in_sam_header = NULL;
    bam1_t *bamdata = NULL;
    int ret_r = 0;
    int ret = EXIT_FAILURE;

    if (argc != 3) {

        return -1;
    }

    inname = argv[1];

    /* 1. open the BAM file */
    inputfile = sam_open(inname, "r");
    if (!inputfile) {
        fprintf(stderr, "Error: Could not open BAM file '%s'\n", inname);
        goto cleanup;
    }

    /*2. read the header*/
    in_sam_header = sam_hdr_read(inputfile);
    if (!in_sam_header) {
        fprintf(stderr, "Error: Could not read BAM header from '%s'\n", inname);
        goto cleanup;
    }

    /*3. allocate a BAM record*/
    bamdata = bam_init1();
    if (!bamdata) {
        fprintf(stderr, "Error: Failed to allocate BAM record\n");
        goto cleanup;
    }

    /*4. loop thru records*/
    int record_count = 0;
    fprintf(fp, "This file was autogenerated by vvcf. Do not modify.\n");
        fprintf(fp, "\n");
    
    /* main read loop */
    while ((ret_r = sam_read1(inputfile, in_sam_header, bamdata)) >= 0) {
        extract_variants(bamdata, in_sam_header, tally);
        const char *qname = bam_get_qname(bamdata);
        const char *rname = sam_hdr_tid2name(in_sam_header, bamdata->core.tid);
        uint32_t *cigar     = bam_get_cigar(bamdata);
        int pos = bamdata->core.pos + 1;  // 0-based to 1-based
        int mapq = bamdata->core.qual;
        int l_qseq = bamdata->core.l_qseq;
        int flag   = bamdata->core.flag;
        int i;
        
 /*       fprintf(fp, "%d: %s\t%s\t%d\t%d\t%d\t%d\n",
               record_count,
               qname ? qname : "",
               rname ? rname : "",
               pos,
               mapq,
               l_qseq,
               flag);

    for(i = 0; i < bamdata->core.n_cigar; i++){
        fprintf(fp, "CIGAR: %d%c", bam_cigar_oplen(cigar[i]), bam_cigar_opchr(cigar[i]));
        fprintf(fp, "\n");
        }*/

        record_count++;

        // limit output for testing, don't do the whole file!!
        /* TODO: REMOVE BEFORE DAY 10 */
        // if (record_count >= 10000) break;
    }

    if (ret_r < -1) {
        fprintf(stderr, "Error reading BAM file (code: %d)\n", ret_r);
        goto cleanup;
    }

    print_tally(fp, tally);
    printf("Processed %d records.\n", record_count);
    ret = EXIT_SUCCESS;

cleanup:
    if (bamdata) bam_destroy1(bamdata);
    if (in_sam_header) sam_hdr_destroy(in_sam_header);
    if (inputfile) sam_close(inputfile);
    return ret;
}
